 version: "3.3"
services:
	app : 
	image : nginx:latest
	ports:
		-80:80
	volumes:
	- ./php:/code:ro
	- ./config/default.conf:/etc/nginx/conf.d/default.conf:ro

	depends_on:
	- php-1
	- php-2
	- php-3

	php -1:
		build:
		context:
		dockerfile: config/Dockerfile

	ports:
		-9000
	volumes:
	- ./html:/var/www/html
	- ./config/session.ini:/usr/local/etc/php/conf.d/session.ini : ro
	depends_on:
	-redis

	php -2:
		build:
		context:
		dockerfile: config/Dockerfille
	ports:
		-9000
	volumes:
		- ./html:/var/www/html
		- ./config/session.ini:/usr/local/etc/php/conf.d/session.ini : ro
	depends_on:
		- redis

	php -3:
		build:
		context:
		dockerfile: config/Dockerfile
	ports:
		- 9000
	volumes:
		- ./html:/var/www/html
		- ./config/session.ini : /usr/local/etc/php/conf.d/session.ini : ro
	depends_on:
		- redis
	redis:
		image : redis:3.2
